<?php
/*
 * This file generated by TrusCRUD.
 *
 * (c) M. Yusup Hamdani <me@dani.work>
 * website: www.truslabs.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/
namespace TrusCRUD\Generator\CRUD;

use TrusCRUD\Generator\CrudGenerator;

class Invitation extends CrudGenerator {

    public function initial() {
        $this->setName('Invitation');
        $this->setSearchable('name');
        $this->withMenu(true); //FALSE = menu not generate
        $this->withUUID(true);
        
        $this->addColumn('groom_name', 'string');
        $this->addColumn('bride_name', 'string');
        
        $this->addColumn('ceremony_datetime', 'datetime');
        
        $this->addColumn('party_datetime', 'datetime');
        $this->addColumn('party_datetime', 'datetime');
        
        $this->addColumn('address', 'text');
        $this->addColumn('coordinate', 'string');
        
        $this->addColumn('father_grooom_name', 'string');
        $this->addColumn('mother_grooom_name', 'string');

        $this->addColumn('father_bride_name', 'string');
        $this->addColumn('mother_bride_name', 'string');
    }

}