<?php
/*
 * This file generated by TrusCRUD.
 *
 * (c) M. Yusup Hamdani <me@dani.work>
 * website: www.truslabs.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/
namespace TrusGenerator;
use TrusCRUD\Generator\CrudGenerator;

class Invoice extends CrudGenerator {

    public function initial() {
        $this->setName('Invoice');
        $this->setSearchable('no_invoice');
        $this->withMenu(true); //FALSE = menu not generate
        $this->withUUID(false);

        $this->addColumn('purchase_id', 'bigInteger')->relation('belongsTo', 'Purchase');
        $this->addColumn('no_invoice', 'string');
    }

}