<?php
/*
 * This file generated by TrusCRUD.
 *
 * (c) M. Yusup Hamdani <me@dani.work>
 * website: www.truslabs.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/
namespace TrusGenerator;
use TrusCRUD\Generator\CrudGenerator;

class Purchase extends CrudGenerator {

    public function initial() {
        $this->setName('Purchase');
        $this->setSearchable('project_name');
        $this->withMenu(true); //FALSE = menu not generate
        $this->withUUID(false);

        $this->addColumn('no_contract', 'string');
        $this->addColumn('project_name', 'string');
        $this->addColumn('customer', 'string');
        $this->addColumn('total_contract', 'integer');
        $this->addColumn('status_contract', 'integer');

    }

}