<?php
/*
 * This file generated by TrusCRUD.
 *
 * (c) M. Yusup Hamdani <me@dani.work>
 * website: www.truslabs.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/
namespace TrusGenerator;
use TrusCRUD\Generator\CrudGenerator;

class Purchase extends CrudGenerator {

    public function initial() {
        $this->setName('Purchase');
        $this->setSearchable('nama_project');
        $this->withMenu(true); //FALSE = menu not generate
        $this->withUUID(false);

        $this->addColumn('no_purchase_order', 'string');
        $this->addColumn('nama_project', 'string');
        $this->addColumn('customer', 'string');
        $this->addColumn('nominal_purchase_order', 'integer');
        $this->addColumn('status_delivery', 'integer');

    }

}