<?php
/*
 * This file generated by TrusCRUD.
 *
 * (c) M. Yusup Hamdani <me@dani.work>
 * website: www.dani.work
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
*/
namespace App\Http\Controllers;

use App\Models\Contract;
use Illuminate\Http\Request;
use App\Models\Invoice;
use Illuminate\Support\Facades\DB;


class InvoiceController extends Controller
{

    protected $view  = 'invoice';

    function __construct()
    {
        parent::__construct();
        $this->base             = route($this->view.'.index');
        $this->data['resource'] = $this->view;
        $this->view             = $this->template.$this->view;
    }

    public function index(Invoice $model, Request $req) {

        if($req->get('search') != '') {

            $serach = strtolower($req->get('search'));

            $model = $model->where(DB::raw('LOWER(no_invoice)'), "LIKE", "%$serach%");
        }
        
        if($req->get('status') != '') {
            $model = $model->where('status', $req->get('status'));
        }

        $this->data['results'] = $model->orderByDesc('id')->paginate(10);

        return view($this->view.'.index', $this->data);
    }

    public function create() {
        return view($this->view.'.form', $this->data);
    }

    public function show() {

    }

    public function edit(Invoice $model, $id) {
        $data = $model->find($id);
        $data->periode_invoice = array_map(fn($x) => date('d/m/Y', strtotime($x)), explode(' s/d ', $data->periode_invoice));
        $this->data['data'] = $data;

        return view($this->view.'.form', $this->data);
    }

    public function store(Invoice $model, Request $req) {

        try {   
            DB::beginTransaction();
            if(isset($req->id)) {
                $model = Invoice::find($req->id);
            }

            $peirode_invoice         = array_map(function($x) {
                $tanggal = implode('-', array_reverse(explode('/', $x)));
                return $tanggal;
            }, $req->bill);

			$model->date_invoice        = implode('-', array_reverse(explode('/', $req->date_invoice)));
			$model->contract_id         = $req->contract_id;
			$model->no_invoice          = $req->no_invoice;
			$model->keterangan         = $req->keterangan;
            $model->total_invoice       = getInt($req->total_invoice);
			$model->total_bayar         = getInt($req->total_bayar);
			$model->total_sisa          = getInt($req->total_sisa);
            
            $model->periode_invoice     = implode(' s/d ', $peirode_invoice);
            $model->status              = $req->status;
            
            $model->save();

            if($req->status == 'PAID') {
                $contract = Contract::find($req->contract_id);
                $contract->decrement('balance', $model->total_invoice);
            }

            $status  = 'success';
            $message = "Save Successfully";
            DB::commit();
        } catch (\Exception $er) {
            dd($er);
            DB::rollBack();
            $status  = 'error';
            $message = $er->getMessage();
        }

        if($req->get('format') == 'json') {
            $response = [
                'status' => $status,
                'message' => $message,
            ];
            return response()->json($response);
        }

        return redirect($this->base)->with('status', $status)->with('message', $message);
    }


    public function update() {

    }

    public function destroy(Invoice $model, $id) {

        try {
            $model->where('id', $id)->delete();
            $status  = true;
            $message = 'Delete Successfully.';
        } catch (\Exception $err) {
            $status  = false;
            $message = $err->getMessage();
        }

        $output['status']   = $status;
        $output['message']  = $message;

        return response()->json($output);
    }

}
